### ISSUE TITLE
Why do you import audio effect? Anyway good work here

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad21-practical-2---android-activity-CalebChoo1#2]
https://github.com/MAD11877/mad21-practical-2---android-activity-CalebChoo1/blob/d8df218043e679d7ca0c9c9633d616bc8d594183/app/src/main/java/sg/edu/np/madpractical2_activity_s10205375/User.java#L3

**Comment by CalebChoo1** [comment]
oh im not sure, will remove it.
